### ISSUE TITLE
Install Request:  DSSP (IN:02766528)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#137]
A user has requested DSSP to be installed to be used with GROMACS: http://manual.gromacs.org/programs/gmx-do_dssp.html

**Comment by ikirker** [comment]
Trying to compile DSSP (<http://swift.cmbi.ru.nl/gv/dssp/>) for this gives me a face full of serious-looking C++ errors.

**Comment by lanselibai** [comment]
Dear Ian, thank you for your effort, could you please share your errors, and I may search it for some answers?

**Comment by ikirker** [comment]
@lanselibai 

Hmm, so, originally I hit a bunch of problems and some checking suggests that the *fatal* ones are because some C++ syntax changed meaning between C++0x and C++11. Telling `g++` to use the older standard of C++ results in a build that then fails because we don't have static versions of some common compression libraries installed. 

Changing it to use the dynamic versions of those libraries instead successfully builds `mkdssp`.

So to build version 3.0.0:
```
$ module purge
$ module load gcc-libs
$ module load compilers/gnu/4.9.2
$ module load python/2.7.12
$ module load boost/1_63_0/gnu-4.9.2
$ wget ftp://ftp.cmbi.ru.nl/pub/software/dssp/dssp-3.0.0.tgz
$ tar -xzf dssp-3.0.0.tgz 
$ cd dssp-3.0.0
$ sed -i -e s/-static// makefile
$ make CXX="g++ -std=c++0x"
```

So, in general, yes, on our clusters you're free to copy over or download, build, and use any software that doesn't either compromise the machine, compromise other users, or bring us legal trouble (e.g. software you're not licensed to use).

So now that we've worked out the problems with this, we can create a central copy tomorrow *or* if you'd prefer, you can build it, using the commands above, in your own home directory space.

The website suggests that you'll have to manage the database part in your own home or scratch directories, otherwise you won't be able to write to it. The `rsync` command to do this using the commands on the page is available, though.

**Comment by lanselibai** [comment]
@ikirker thanks a lot for your help!

If I understand correctly:
1) I will wait for your central copy tomorrow.
2) do the "Starting your in-house DSSP database":
rsync -avz rsync://rsync.cmbi.ru.nl/dssp/ /path_to_dssp/
3) test if “gmx do_dssp” is okay

**Comment by ikirker** [comment]
This is now installed. The Boost module needs a module for a version of Python loaded, but for this purpose it doesn't matter which since the parts of Boost that use Python aren't used by DSSP as far as I'm aware.

```
$ module load gcc-libs/4.9.2
$ module load python/3.6.3
$ module load boost/1_63_0/gnu-4.9.2
$ module load dssp/3.0.0/gnu-4.9.2
$ mkdssp
mkdssp 3.0.0 options:
[...]
```

@lanselibai Those steps look correct, but be aware:

 - /path_to_dssp/ should be replaced with a path somewhere in your home directory or scratch space
 - you may need to set a DSSP environment variable to point to it, or at least that's what that email you linked to suggests
 - if you're using MPI versions of GROMACS I assume it'll be `gmx_mpi` instead of `gmx`

**Comment by lanselibai** [comment]
@ikirker thank you very much!

I am waiting for the 
rsync -avz rsync://rsync.cmbi.ru.nl/dssp/ ~/Scratch/0_module/dssp/

Do you mean my job file should be like this:

#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=1:00:0
#$ -l mem=2G
#$ -l tmpfs=15G
#$ -N MD
#$ -pe mpi 4
#$ -cwd 

module unload compilers mpi
module load compilers/intel/2015/update2
module load mpi/intel/2015/update3/intel
module load gromacs/5.1.1/intel-2015-update2

module load gcc-libs/4.9.2
module load python/3.6.3
module load boost/1_63_0/gnu-4.9.2
module load dssp/3.0.0/gnu-4.9.2
mkdssp

setenv DSSP /home/uc????/Scratch/0_module/dssp

echo 1 | gmx_mpi do_dssp -f md_0_1_noPBC.xtc -s md_0_1.tpr -ssdump ssdump.dat -map ss.map -o ss.xpm -sc scount.xvg -a area.xpm -ta totarea.xvg -aa averarea.xvg -tu ns

**Comment by ikirker** [comment]
Ah, sorry, I misread the email. The DSSP variable should be set to the path to `mkdssp`. 

I'm not sure why you've put that "echo 1" part there: I don't think it's necessary?

And, I'm not sure whether GROMACS can actually do this in parallel, so there may actually be no use for the `gmx_mpi` part.

And, the gcc-libs module is actually loaded by default, so you can leave it out.

So, possibly this:

```bash
#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=1:00:0
#$ -l mem=2G
#$ -l tmpfs=15G
#$ -N MD
#$ -cwd

module unload compilers mpi
module load compilers/intel/2015/update2
module load mpi/intel/2015/update3/intel
module load gromacs/5.1.1/intel-2015-update2

module load python/3.6.3
module load boost/1_63_0/gnu-4.9.2
module load dssp/3.0.0/gnu-4.9.2

export DSSP="$(which mkdssp)"

gmx do_dssp -f md_0_1_noPBC.xtc -s md_0_1.tpr -ssdump ssdump.dat -map ss.map -o ss.xpm -sc scount.xvg -a area.xpm -ta totarea.xvg -aa averarea.xvg -tu ns
```

**Comment by lanselibai** [comment]
thank you very much! it works now!

`echo 1` is to select the index needed to calculate the dssp.

But is it necessary to run `rsync -avz rsync://rsync.cmbi.ru.nl/dssp/ /path_to_dssp/` as shown in [here](http://swift.cmbi.ru.nl/gv/dssp/) ?

**Comment by ikirker** [comment]
I don't think so: I think that's a database of pre-created files, whereas here you're creating new ones with DSSP within GROMACS.

**Comment by lanselibai** [comment]
yes, I agree, after running `rsync -avz rsync://rsync.cmbi.ru.nl/dssp/ /path_to_dssp/`, I got loads of dssp files from different proteins. 

Thank you so much!

**Comment by heatherkellyucl** [comment]
Closing: no reports of further errors.
