### ISSUE TITLE
vt and snpEFF (IN:0309165)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#190]
A user has requested both these packages.

https://genome.sph.umich.edu/wiki/Vt#Installation

https://sourceforge.net/projects/snpeff/?source=directory

**Comment by ikirker** [comment]
vt appears to have a somewhat loose approach to versioning, and recommends you build it straight from the git master/HEAD.

I thought about labelling it with the first N characters of the HEAD hash, but that felt kind of user-hostile, especially since it wouldn't be ordered if we installed a new version.

So, the build script currently gets the date of the most recent commit and uses that as the version label. Does that seem reasonable?

**Comment by ikirker** [comment]
Also I'm a little confused at what to do with snpEFF. It comes as a zip that unpacks to two JAR files, a directory of examples, and a directory of scripts. I... Guess add the scripts dir to the path, but then maybe also add scripts to run the JARs if none of them do it already? The docs imply you're just supposed to do the `java -jar thing.jar` yourself, which seems a little unnecessary. Also the default config file location appears to be the current working directory? This package is confusing. -_-

**Comment by ikirker** [comment]
vt installed everywhere, snpEff not being installed -- user running from their own downloaded copy. (See: IN:03091651.)
