### ISSUE TITLE
Autodock Vina and openbabel

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#253]
IN:03543980

http://vina.scripps.edu/
Has binaries available. 

(Am checking if VinaLC, the MPI parallel version from Lawrence Livermore that we have installed already is sufficient - https://plsuser.llnl.gov/bbs/vinalc/. We have `vinalc/1.1.2/gnu-4.9.2`).

http://openbabel.org/wiki/Main_Page

**Comment by ikirker** [comment]
OpenBabel is straightforward enough to build (though maybe some users might need more bindings):

```
module purge
module load \
gcc-libs/4.9.2 \
compilers/gnu/4.9.2 \
libxml2/2.9.4/gnu-4.9.2 \
eigen/3.2.5/gnu-4.9.2 \
python/3.7.2 \
python3/3.7
mkdir build
cd build
cmake ../ \
  -DCMAKE_INSTALL_PREFIX="$install_prefix" \
  -DBUILD_DOCS=ON \
  -DENABLE_OPENMP=ON \
  -DOPTIMIZE_NATIVE=ON
make -l 8 -j
```

But then the tests will fail, because:
 - something in the test process is wiping the environment, and it can't get a suitably up-to-date `libstdcxx.so`
 - one of the tests has a mixed-spaces-and-tabs problem in the Python code, which I'm guessing isn't treated as an error in the version of Python the developers are using, but sure is in 3.7.

You can work around the environment problems by wrapping the `test_runner` and `test_inchiwrite` binaries, as shown below. Note this must be done **after** the build is complete. Also note that the `pytest_sym` test takes *much* longer on more threads -- running the test on 36 cores will often time out. To mitigate that, run the tests with `taskset`, as shown below. The final thing is to fix the broken tabs-vs-spaces thing. Which we can do by replacing the tabs with 8 spaces.

```
mv bin/test_runner bin/test_runner.x
mv bin/test_inchiwrite bin/test_inchiwrite.x
cat >bin/test_runner <<EOF
#!/bin/bash

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export PATH="$PATH"

exec $(pwd)/bin/test_runner.x "\$@"
EOF
cat >bin/test_inchiwrite <<EOF
#!/bin/bash

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export PATH="$PATH"

exec $(pwd)/bin/test_inchiwrite.x "\$@"
EOF
chmod +x bin/test_inchiwrite bin/test_runner

sed -i -e 's/\t/        /g' ../test/testpdbformat.py

taskset -c 0,1,2,3 make test
```

I'll write this up as a build script.

**Comment by ikirker** [comment]
Written up. Installed everywhere except Legion, due to on-going network issues. Requires `libxml2` on top of the default modules, *e.g.*:

```
[uccaiki@login13 ~]$ module purge
[uccaiki@login13 ~]$ module load default-modules
[uccaiki@login13 ~]$ module load libxml2
[uccaiki@login13 ~]$ module load openbabel
[uccaiki@login13 ~]$ obchiral
Usage: obchiral <filename>
[uccaiki@login13 ~]$ which obchiral
/shared/ucl/apps/openbabel/2.4.1/gnu-4.9.2/bin/obchiral
[uccaiki@login13 ~]$
```

**Comment by heatherkellyucl** [comment]
Emailed user.

**Comment by ikirker** [comment]
OpenBabel now installed on all clusters including Legion.
