### ISSUE TITLE
TensorFlow 1.13

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#258]
IN:03567236

Adds more features for deep learning models. CPU and GPU versions wanted.

**Comment by owainkenwayucl** [comment]
Ok, thanks to Nvidia + Google this will be hard.

Tensorflow 1.13 requires CUDA >= 10.
CUDA 10 requires a new driver for the GPUs.

**Comment by owainkenwayucl** [comment]
(there's no 1.13.0, only 1.13.1 for reasons)

**Comment by owainkenwayucl** [comment]
The CPU (plan and MKL versions) are installed.

**Comment by owainkenwayucl** [comment]
I've installed the GPU version but it won't work until we can upgrade the drivers.

Fun aside.

NVidia are aware that the Cuda <-> Driver mapping problem is an issue so for Tesla cards and Cuda >= 10.0 there's this concept of forward compatibility where you can use a newer version of Cuda with an older driver, on the Tesla platform (only?).

![Forward Compatibility](https://user-images.githubusercontent.com/4256093/55011497-dddb1500-4fdd-11e9-82cb-1fbf5d9ae642.png)

Doing this is... tricky, because the forward compatibility drivers are only included in the RPM "Network" version of their Cuda distribution, and of course without them it doesn't work.

With them it doesn't work either because it transpires that the forward compatibility thing only works with specific versions of the Tesla drivers and ours are slightly too new :(

**Comment by owainkenwayucl** [comment]
As a fun aside 2.0, the installer for Cuda 10.1 is radically different from the one used for all versions up until this point, inc. Cuda 10.0 and it doesn't currently work with our install script.

Oh, and it fails silently.

**Comment by owainkenwayucl** [comment]
Cuda 10.0, the new drivers, CUDNN etc are all deployed and this is tested and working.

**Comment by heatherkellyucl** [comment]
Example modules for using the GPU version:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load python3/recommended
module load cuda/10.0.130/gnu-4.9.2
module load cudnn/7.4.2.24/cuda-10.0
module load tensorflow/1.13.1/gpu
```
