### ISSUE TITLE
UbPred: Install on Myriad [IN03572464]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#260]
http://www.ubpred.org/

Might depend on an old Matlab runtime (R2008a)?

**Comment by ikirker** [comment]
UbPrep wants a 32-bit Matlab runtime, which is downloadable from the same website. But 32-bit Matlab wants 32-bit ncurses (`libncurses.so.5`, specifically) and possibly also libgfortran (needed by Matlab's `refblas.so` which may or may not be necessary), which it doesn't ship with. It may also want 32-bit X (`libXp.so`), but it's possible that can be avoided if we're not using any GUI stuff.

32-bit ncurses needs 32-bit GCC, including G++, which the system version of GCC doesn't include.

And I think our 4.9.2 version was built without 32-bit capability, because I didn't think we'd ever need it.

----

Okay, so I grabbed the Centos 7 RPMs for 32-bit NCurses and `libXp.so` (it turns out it *is* necessary), and those work with a manually-installed Matlab runtime, but now I'm trying to work out how to script that runtime install -- it uses an ancient and extremely unhelpful version of InstallShield. I could *probably* grab the newer stable release of the same major version from the Matlab release, but there'd be no way to tell whether it was working correctly.

This would be easier if the software had been recompiled in the last 10 years. Or was open-source.

----

Which actually raises a question. This software is not released under any actual license, which means that no use of it is permitted. (All rights reserved.)

So we can't do anything with it. :eyes:

**Comment by ikirker** [comment]
Oh, and just for the record: the command to extract an rpm is: `rpm2cpio file.rpm | cpio -idmv`

**Comment by ikirker** [comment]
I've contacted the authors, they're going to check with their institution.

**Comment by ikirker** [comment]
We have a tacit agreement from the authors to use this. I've installed it on Myriad along with its associated 32-bit libraries and really surprisingly old Matlab runtime distribution, and a `ubpred.local` script that handles the complexities of running the weird Matlab launcher script and that the binary wants to have some distributed `.mat` files in the current working directory.

**Comment by ikirker** [comment]
Notified requester.

**Comment by ikirker** [comment]
(Also installed on Legion.)

**Comment by balston** [comment]
Really done!
