### ISSUE TITLE
WRF and Chimere

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#267]
IN:03527852

### WRF

Weather Research and Forecasting Model WRF (https://www.mmm.ucar.edu/weather-research-and-forecasting-model)
https://github.com/wrf-model/WRF

License:
> NCAR and UCAR make no proprietary claims, either statutory or otherwise, to this version and release of WRF and consider WRF to be in the public domain for use by any person or entity for any purpose without any fee or charge

Add to module file:
> We request that all new users of WRF please register. This allows us to better determine how to support and develop the model. Please register using this form: http://www2.mmm.ucar.edu/wrf/users/download/wrf-regist.php.

### Chimere

http://www.lmd.polytechnique.fr/chimere/
GNU GPL

**Comment by heatherkellyucl** [comment]
WRF seems to require the user put the input files in the directory with the executables - might need to provide a buildscript only.

**Comment by owainkenwayucl** [comment]
From what I recall it's a fairly terrible build process - a shell script that runs but doen't terminate when something breaks.  One thing we probably want to do is patch in `set -e` everywhere...

**Comment by doyarzunv** [comment]
Hi Heather
I just came back from Chimere training, and I got a new version of the model. In this new version, both WRF and Chimere compile together, so there is no need of installing WRF separately. The developers configured this new installation files to make both models compile together. In theory, the installation-compilation should be smoother (and at once for both models).  Considering the above and that to the date there are no milestones yet I would like to ask for the installation of this new version.
I have the files with me. I know that an option would be me to do the installation in my account in Grace. However, I may require some help in compiling and not sure which option is better for you at the end. Should I share the files here?. Thank you very much for your time

**Comment by heatherkellyucl** [comment]
@doyarzunv Do the input files still need to be in the WRF install directory? If so, then the install does need to be in your space so you're able to run it. Don't put files here, but tell us about any errors you get (and if you say we have permission to look at your files in a support ticket, we can look at your account).

**Comment by doyarzunv** [comment]
@heatherkellyucl I don't think so, but I will check that to be completely sure. CHIMERE requires that the input - big files (e.g. meteorology) are in a directory I can modify, but not necessarily the same. I would need the required libraries paths. Not sure how to deal with this, should I install them in my account? (I don't have previous experience with HPC at UCL). I'm copying here this section of the guidance for compilation, given references to the computer I was using at the training (sorry for the long text, but I guess is the more effective way to show you what I would need):

----------------------------------------------------------------------------
The first step is to configure the scripts containing the path of all required libraries.
In the distributed version, the Makefile already designed to compile the model is available for two different compilers: ifort and gfortran. These files are proposed in the /home/myaccount/CHIMERE/makefiles.hdr/ directory. For example, for gfortran, the filename is Makefile.hdr.gfortran-64-ompi. All rules necessary to compile CHIMERE and OASIS are in this file. In this file, paths for the libraries are defined as configurable variables:

NETCDFLIB       =       $(my_netcdflib) 
NETCDFINC       =       $(my_netcdfinc)
HDF5LIB         =       $(my_hdflib) 
HDF5INC         =       $(my_hdfinc)
GRIBLIB         =       $(my_griblib) 
GRIBINC         =       $(my_gribinc)
BLITZLIB        =       $(my_blitzinc)

In order to provide the correct paths to this makefile, you have to configure the mychimere.sh file. Some examples are provided with the distributed model version, but you have to change them and adapt them to your local configuration. The file must indicates important pathes such as:

⋄ location of your compilers : Fortran (77, 90), C, C++
⋄ location of your parallel HDF5 package
⋄ location of your NetCDF package compiled with parallel HDF5
⋄ location of your MPI library and executables
⋄ if needed, location of your gribex library (for interfaces to meteorological datasets in the grib format)

Note in this version, there is no need of pNetCDF package.Finally, for CHIMERE to find these files without problem, you have to create a link in the src/ directory such as:
lrwxrwxrwx  Makefile.hdr -> ../makefiles.hdr/Makefile.hdr.gfortran-64-ompi
lrwxrwxrwx  mychimere.sh -> ../mychimere.chims.gfortran.nc4

The rest should be just compile following:
./build-chimere.sh
./build-wrf.sh

**Comment by mmistry4** [comment]
Not 100% sure about this one, has it been done the original remfo ticket has been closed
