### ISSUE TITLE
Install Request: Elk v.6.3.2

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#336]
IN:04157418 

> I was wondering whether Elk version 6.3.2 could be installed on THOMAS: https://sourceforge.net/projects/elk/files/, and linked to the libxc code please? It is open-source under the GNU license. It has considerable efficiency increases over the previous versions with new functionalities required for the system I am trying to study.

**Comment by ikirker** [comment]
Trying 6.8.4 instead since it was released since we got this message.

It builds fine, but libwannier (which it statically links against) fails one of its tests on Thomas and Michael, slightly exceeding the failure tolerance on numerical precision.

I submitted an issue and there's a post-release commit that relieves the tolerances and lets it build, so I'm patching that in.

Seems to work, installed everywhere that's up (that's not Grace and not Legion).

**Comment by heatherkellyucl** [comment]
Done in Sept.
