### ISSUE TITLE
Install request: PostGIS

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#46]
The shipping group need PostGIS installed:

http://postgis.net/source/

Most of the dependencies are already installed but we'll want to do a central install of postgres.

**Comment by ikirker** [comment]
## Requirements

*(copy/pasted from the installation instructions with some abbreviation and paraphrasing)*

### Required

- [ ] PostgreSQL 9.1 or higher. A complete installation of PostgreSQL (including server headers) is required. PostgreSQL is available from <http://www.postgresql.org> .
- [x] GNU C compiler (gcc). Some other ANSI C compilers can be used to compile PostGIS, but we find far fewer problems when compiling with gcc.
- [x] GNU Make (gmake or make). 
- [ ] Proj4 reprojection library, version 4.6.0 or greater. The Proj4 library is used to provide coordinate reprojection support within PostGIS. Proj4 is available for download from <http://trac.osgeo.org/proj/> .
- [ ] GEOS geometry library, version 3.3 or greater, but GEOS 3.5+ is recommended to take full advantage of all the new functions and features. GEOS is available for download from <http://trac.osgeo.org/geos/> and 3.4+ is backward-compatible with older versions so fairly safe to upgrade.
- [ ] LibXML2, version 2.5.x or higher. LibXML2 is currently used in some imports functions (ST_GeomFromGML and ST_GeomFromKML). LibXML2 is available for download from <http://xmlsoft.org/downloads.html>.
- [ ] JSON-C, version 0.9 or higher. JSON-C is currently used to import GeoJSON via the function ST_GeomFromGeoJson. JSON-C is available for download from <https://github.com/json-c/json-c/releases/>.
- [ ] GDAL, version 1.8 or higher (1.9 or higher is strongly recommended since some things will not work well or behavior differently with lower versions). This is required for raster support and to be able to install with CREATE EXTENSION postgis so highly recommended for those running 9.1+. <http://trac.osgeo.org/gdal/wiki/DownloadSource>. 

### Optional

- [ ] Whatever GDAL Raster formats you need.
- [ ] GTK (requires GTK+2.0, 2.8+) to compile the shp2pgsql-gui shape file loader. <http://www.gtk.org/> .
- [ ] SFCGAL, version 1.1 (or higher) could be used to provide additional 2D and 3D advanced analysis functions to PostGIS cf Section 8.10, “SFCGAL Functions”. And also allow to use SFCGAL rather than GEOS for some 2D functions provided by both backends (like ST_Intersection or ST_Area, for instance). A PostgreSQL configuration variable postgis.backend allow end user to control which backend he want to use if SFCGAL is installed (GEOS by default). Nota: SFCGAL 1.2 require at least CGAL 4.3 and Boost 1.54 (cf: <http://oslandia.github.io/SFCGAL/installation.html>) <https://github.com/Oslandia/SFCGAL>.
- [ ] In order to build the Chapter 12, Address Standardizer you will also need PCRE <http://www.pcre.org> (which generally is already installed on nix systems). Regex::Assemble perl CPAN package is only needed if you want to rebuild the data encoded in parseaddress-stcities.h. Chapter 12, Address Standardizer will automatically be built if it detects a PCRE library, or you pass in a valid --with-pcre-dir=/path/to/pcre during configure.
- [ ] CUnit (CUnit). This is needed for regression testing. <http://cunit.sourceforge.net/>
- [ ] DocBook (xsltproc) is required for building the documentation. Docbook is available from <http://www.docbook.org/> .
- [ ] DBLatex (dblatex) is required for building the documentation in PDF format. DBLatex is available from <http://dblatex.sourceforge.net/> .
- [ ] ImageMagick (convert) is required to generate the images used in the documentation. ImageMagick is available from <http://www.imagemagick.org/> .

**Comment by ikirker** [comment]
Of the above, only GCC, GNU make, proj4, and GDAL are installed already.

**Comment by ikirker** [comment]
JSON-C 0.12 won't build with GCC 4.9.2 because `-Werror -Wall` hits a `-Werror=unused-but-set-variable`. Considering remediations.

**Comment by ikirker** [comment]
Build scripts prepared for:

- geos-3.5.0
- json-c-0.12
- libxml2-2.9.4
- postgresql-9.5.3

**Comment by ikirker** [comment]
Build scripts prepared for:

 * cunit-2.1-3
 * pcre2-10.21

Build, installed, added modules for:

 * geos-3.5.0
 * json-c-0.12
 * libxml2-2.9.4
 * postgresql-9.5.3
 * cunit-2.1-3
 * pcre2-10.21

**Comment by ikirker** [comment]
PostGIS needs own, separate installation of PostgreSQL because:
```
------------------------------------------------------------------------
  WARNING: You have set the --prefix to '/dev/shm/postgis-test-install'. But we mostly    
  ignore the --prefix. For your info, using the values determined from 
  /shared/ucl/apps/postgresql/9.5.3/gnu-4.9.2/bin/pg_config we will be installing:   
    * postgis shared library in /shared/ucl/apps/postgresql/9.5.3/gnu-4.9.2/lib 
    * postgis SQL files in /shared/ucl/apps/postgresql/9.5.3/gnu-4.9.2/share/contrib/postgis-2.2 
    * postgis executables in /shared/ucl/apps/postgresql/9.5.3/gnu-4.9.2/bin 
------------------------------------------------------------------------
```

**Comment by ikirker** [comment]
Built, installed, added modules for PostGIS and PostgreSQL together as `postgres+postgis/9.5.3+2.2.2/gnu-4.9.2`.
