### ISSUE TITLE
Install Request: MRtrix 3.0.3 (latest version) [IN05128217]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#473]
MRtrix3 provides a set of tools to perform various types of diffusion MRI analyses: https://www.mrtrix.org/

Build instructions: https://mrtrix.readthedocs.io/en/latest/installation/build_from_source.html

I did a quick test with our existing GNU 4.9.2, Eigen and Qt builds but it fails to compile. It needs at least GNU 5.x and probably a newer Eigen.

**Comment by sgoksan** [comment]
Hi, thank you for adding this request to your jobs. I have an issue related to this. 
MRTrix3 requires python version > 2.7. Some MRTrix3 commands call on FSL scripts (which only uses python 2.X and cannot run with python3). Could the new install of MRTrix3 please also be set up to use python2/recommended?

The reason I am asking this is because I have noticed the following:
When trying to run mrtrix/3.0rc3/gnu-4.9.2/nogui on Myriad, I get the following error messages:
ERROR:151: Module 'mrtrix/3.0rc3/gnu-4.9.2/nogui' depends on one of the module(s) 'python3/3.6'
ERROR:102: Tcl command execution failed: prereq python3/3.6

However when I add python3/3.6 to my path, I then get this error:
ERROR:150: Module 'python/3.6.3' conflicts with the currently loaded module(s) 'python/2.7.12'
ERROR:102: Tcl command execution failed: conflict python

I am not sure how to resolve this. But I thought it might be relevant for the new installation. Cheers.
