### ISSUE TITLE
Gromacs: Investigate problem with Gromacs 2021.5 producing incorrect results with GPUs on Young and Myriad [IN05506952]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#497]
In some(?) cases Gromacs 2021.5 GPU Version is producing incorrect results:
![Graph1](https://user-images.githubusercontent.com/4246274/194902358-f486abcb-898d-4dae-baac-b77fa3aa0867.png)

Users example has been run on both Young and Myriad GPU nodes with results like that shown in the above graph.

See Jira story:

https://ucldata.atlassian.net/browse/RCE-1187

**Comment by balston** [comment]
Files to run the example are attached to the RF ticket.

**Comment by heatherkellyucl** [comment]
Possible things to try (also the MMM Hub user group will get a link to this issue, so we might get some suggestions or other test cases from there):
- NVIDIA NGC container for GROMACS
- Spack GROMACS GPU install

**Comment by owainkenwayucl** [comment]
I've done independent builds on AWS on an Arm system (Graviton 2) with builds of the code from https://github.com/spack/spack so that they share nothing with our builds on our systems and I believe that this is a change in behaviour of GROMACS somewhere between 2018.2 and 2021.5.

That is to say, 2018.2 on Arm from spack  with that set of input files generates msd curves that correspond with the "high" curves in the graph above, 2021.5 on Arm from spack generates msd curves that correspond with the lower curves.

Correspondingly, I've removed the "bug" tag as this is a feature of GROMACS.  I'm doing some further runs to narrow down some exact things around exactly when this change happened and hopefully I can tie it to change in a GROMACS changelog somewhere.

Apologies to anyone who this issue has made concerned about the accuracy of their simulations.

**Comment by owainkenwayucl** [comment]
![msdarm](https://user-images.githubusercontent.com/4256093/224012024-4cfd2b7e-3250-45d3-9627-b182cd47596b.png)

**Comment by owainkenwayucl** [comment]
2023 gives similar output to 2021.

![unicodeplots](https://user-images.githubusercontent.com/4256093/224175436-80c6b1db-c2c0-4ae0-bbaa-2841cfb65f8f.png)

**Comment by owainkenwayucl** [comment]
![arm](https://user-images.githubusercontent.com/4256093/224692316-25baa125-2afd-485e-867b-5fac09788146.png)
![ver_study](https://user-images.githubusercontent.com/4256093/224692330-af71a785-9b48-4ef9-a490-67b23377e194.png)

**Comment by owainkenwayucl** [comment]
Note: the difference in scale is due to the user graphing MSD for water only - the simulation consists of a rigid carbon + metal oxide structure with water in it. The rigid structure does not move (it has an MSD of 0).

```
Select a group to calculate mean squared displacement for:
Group     0 (         System) has 12189 elements
Group     1 (          Other) has  4374 elements
Group     2 (            MOF) has  4374 elements
Group     3 (          Water) has  7815 elements
Group     4 (            SOL) has  7815 elements
Group     5 (      non-Water) has  4374 elements
```

Since MSD is *mean*, graphing the whole system rather than the water/solvent just scales the curve.

**Comment by owainkenwayucl** [comment]
To make things even more confusing, there is an aspect of this which is the GROMACS MSD command itself:

![msd](https://user-images.githubusercontent.com/4256093/225152000-4541515b-b38e-4d66-9e80-b257f0d5f724.png)

This is not enough of an effect to result in the difference between "historical" and "modern" GROMACS but it is still a big change.

**Comment by owainkenwayucl** [comment]
It is my belief at this point that we have shown that GROMACS 2021.5 is producing the same results at UCL as elsewhere in the world and therefore I am closing this issue for now.

A longer write-up may follow in blog form.

**Comment by owainkenwayucl** [comment]
It does indeed correspond to this change. `-pbc` is default, `-nopbc` seg faults with that input.
