### ISSUE TITLE
Install CUDA 8.0 (with OpenCL)

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#85]
Required for Tensorflow 1.0 #57 

Also needs libcupti-dev (NVIDIA CUDA Profile Tools Interface) which we may get anyway by installing from source.

**Comment by heatherkellyucl** [comment]
Also check for OpenCL support, since that is supposed to be part of the package now.

Sounds like it is an interactive install option.

**Comment by owainkenwayucl** [comment]
There appear to be neither interactive, nor command-line options for OpenCL.

**Comment by owainkenwayucl** [comment]
Really interestingly, there's an Arch package for nVidia OpenCL which extracts it from the nVidia XFree86 drivers: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/nvidia-utils

**Comment by owainkenwayucl** [comment]
It would seem sensible to try and compile an OpenCL program to test, but the nVidea OpenCL examples (https://developer.nvidia.com/opencl) don't compile, not because of an OpenCL problem, but because they are missing some `Makefile`s (and possibly other files) that they do recursive `make` on.  I get the impression nVidia really really really really don't want you to use OpenCL.

Also, there is apparently no such thing as a "simple" OpenCL program.

Anyway, digging about on tutorial sites,  I've found that the OpenCL headers for non-Apple platforms are `CL/cl.h` which is present on both our installs:

```none
Legion [login06] cuda ☻ ➤ find . -name cl.h
./7.5.18/gnu-4.9.2/include/CL/cl.h
./8.0.61/gnu-4.9.2/include/CL/cl.h
```

This at least means we don't need to construct the equivalent of arch's `opencl-headers` package.

We also have a bunch of `libOpenCL.so`s:

```none
Legion [login06] cuda ☻ ➤ find . -name *OpenCL*
./7.5.18/gnu-4.9.2/lib64/libOpenCL.so
./8.0.61/gnu-4.9.2/lib64/libOpenCL.so
./8.0.61/gnu-4.9.2/lib64/libOpenCL.so.1.0.0
./8.0.61/gnu-4.9.2/lib64/libOpenCL.so.1.0
./8.0.61/gnu-4.9.2/lib64/libOpenCL.so.1
```

I'm stull digging.

**Comment by owainkenwayucl** [comment]
Poking about on problems people have on stackoverflow, it looks like the file `/etc/OpenCL/vendors/nvidia.icd` is important which could be problematic for all kinds of reasons.

**Comment by owainkenwayucl** [comment]
As in, without it, we can have the tools for compiling but things won't compile.

I've logged into the single P-class node, and the files in the `arch` package are on there:

```none
Legion [node-p00a-001] lib64 ☻ ➤ ls /etc/OpenCL/vendors/nvidia.icd 
/etc/OpenCL/vendors/nvidia.icd
Legion [node-p00a-001] lib64 ☻ ➤ ls libnvidia-compiler.so*
libnvidia-compiler.so.352.63
Legion [node-p00a-001] lib64 ☻ ➤ ls libnvidia-opencl.so*
libnvidia-opencl.so.1  libnvidia-opencl.so.352.63
Legion [node-p00a-001] lib64 ☻ ➤ 
```

So they are part of the driver kit.

I suspect this means that the answer to "can I compile stuff for OpenCL on Legion?" is "Yes, but you need to compile on a node with the drivers, i.e. `qrsh -l gpu=1 -ac allow=p ...` or inside a job script.

These files are also present on the V class nodes, so they are also suitable:

```none
Legion [node-v00a-008] ~ ☻ ➤ ls /etc/OpenCL/vendors/nvidia.icd 
/etc/OpenCL/vendors/nvidia.icd
Legion [node-v00a-008] ~ ☻ ➤ cd /usr/lib64
Legion [node-v00a-008] lib64 ☻ ➤ ls *opencl*
libnvidia-opencl.so.1  libnvidia-opencl.so.352.63
Legion [node-v00a-008] lib64 ☻ ➤ ls *compiler*
libnvidia-compiler.so.352.63
```

**Comment by owainkenwayucl** [comment]
Right.  I've installed the toolkit, ascertained the limited degree to which doing so allows users to compile OpenCL code for the nVidia cards, so I'm closing.
